name: better
description: A starting point for Dart libraries or applications.
# version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.9.0'

dependencies:
  collection: 1.14.13-dev
  test: ^1.9.0

# Temporary override as the null safety enabled versions of this package is
# not yet published to pub.dev.
dependency_overrides:
  collection:
    git:
      url: https://github.com/dart-lang/collection
      ref: null_safety
