name: better
description: This package serves as an extension to many dart classes with the goal to provide a more fluid development experience
version: 0.1.0-dev.5
homepage: https://github.com/loganrussell48/better

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  test: ^1.9.0
  pedantic: ^1.9.0
  meta: ^1.2.3
  intl: ^0.16.1

# Temporary override as the null safety enabled versions of this package is
# not yet published to pub.dev.
#dependency_overrides:
#  collection:
#    git:
#      url: https://github.com/dart-lang/collection
#      ref: null_safety
